# Ce flux de travail utilise des actions qui ne sont pas certifiées par GitHub.
# Elles sont fournies par un tiers et sont régies par
# Conditions d'utilisation, politique de confidentialité et assistance distinctes
# documentation.

# Ce flux de travail installera Deno puis exécutera `deno lint` et `deno test`.
# Pour plus d'informations, consultez : https://github.com/denoland/setup-deno

name: Deno

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v5

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # Décommentez cette étape pour vérifier l'utilisation de 'deno fmt' sur chaque commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A
